### PR TITLE
Implement `:ED`

### PR DESCRIPTION
**Pull request by shueybubbles**
`:ed` is a system command

```
e:\git\go-sqlcmd\cmd\sqlcmd>sqlcmd -S davidshi-2019 -X
1> ed
Sqlcmd: Error: ED and !!<command> commands, startup script, and environment variables are disabled.
```

Also, preserve blank lines from input.

Pre-fix:
```
e:\git\go-sqlcmd\cmd\sqlcmd>.\sqlcmd
1> select 100
2>
2>
2>
2>
2> select 200
3> :list
select 100
select 200
3>
```

ODBC:
```
e:\git\go-sqlcmd\cmd\sqlcmd>"C:\Program Files\Microsoft SQL Server\110\Tools\Binn\SQLCMD.EXE"
1> select 100
2>
3>
4>
5>
6> select 200
7> :list
select 100




select 200
7>
```

With Fix:

```
e:\git\go-sqlcmd\cmd\sqlcmd>.\sqlcmd
1> select 100
2>
3>
4>
5>
6> select 200
7> :list
select 100




select 200
7>
```

### CODE REVIEW

**Review by apoorvdeshmukh — COMMENTED** [review]
Should we be disabling ed command if it is not an interactive session?
It's unlikely that one would have ed in their sql script but should we be throwing error if that's the case?

**Review by apoorvdeshmukh — APPROVED** [review]

**Comment by shueybubbles** [comment]
> Should we be disabling ed command if it is not an interactive session? It's unlikely that one would have ed in their sql script but should we be throwing error if that's the case?

The odbc sqlcmd allows `ed` during non-interactive runs.

**Comment by shueybubbles** [comment]
Remember, `sqlcmdeditor` can be set to run some tool that automatically makes changes to the content of the file without any user input. So you could use it to run a perl or awk script etc.

**Comment by shueybubbles** [comment]
@apoorvdeshmukh  or @stuartpa  do you have a working Linux or WSL instance to test this with? My WSL got broken with the Win11 upgrade.

**Comment by apoorvdeshmukh** [comment]
> @apoorvdeshmukh or @stuartpa do you have a working Linux or WSL instance to test this with? My WSL got broken with the Win11 upgrade.

I have WSL instance. Will test this.

**Comment by apoorvdeshmukh** [comment]
On windows I do not see the interactive session being terminated after execution of SQL commands mentioned in editor via ed
```
git\go-sqlcmd>.\sqlcmd.exe
1> ed
1> select @@version
2> go
                                                                                                                        

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)
        Apr 29 2022 18:00:13
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 22621: ) (Hypervisor)


(1 row affected)
1>
```
On WSL I see this getting terminated and there are some whitespace characters thrown
```
~/git/go-sqlcmd$ ./sqlcmd -S192.168.192.1 -Usa
Password:
1> ed
Vim: Warning: Input is not from a terminal
1> select @@version
                   2> go


                                            ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)
                                                                                                                                        Apr 29 2022 18:00:13
                                                                                                                                                                Copyright (C) 2019 Microsoft Corporation
                                                                                                                                                                                                                Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 22621: ) (Hypervisor)


                                                                                            (1 row affected)
                                                                                                            1> ~/git/go-sqlcmd$
```

**Pull request merged**
