### PR TITLE
[Draft] github action added

### PR DESCRIPTION
**Pull request by JyotikaGargg**
Release download count script is added to Github Action .
This gets the data from url : "https://api.github.com/repos/microsoft/go-sqlcmd/releases"

### CODE REVIEW

**Comment by stuartpa** [comment]
Can you add a brief description in the PR of what this PR is for.

**Comment by JyotikaGargg** [comment]
> Can you add a brief description in the PR of what this PR is for.

Experimenting few things . Closing this PR.

**Comment by stuartpa** [comment]
Should this PR be a Draft, or is it ready for review?  I don't understand how this PR fits into the bigger picture.

**Comment by JyotikaGargg** [comment]
> Should this PR be a Draft, or is it ready for review? I don't understand how this PR fits into the bigger picture.



> Should this PR be a Draft, or is it ready for review? I don't understand how this PR fits into the bigger picture.
There was a confusion that happened if we should be using Azure function or Github Action. I created the Github Action . But now i am again focusing on collecting the data on Azure Storage through Azure function.

**Pull request closed without merging**
